/**
 * st export <file.st> --to coq|lean|tptp|json
 *
 * Export a .st proof file to a target format.
 * Uses st-lang's render API for json/markdown formats, and generates
 * basic Coq/Lean/TPTP stubs for formal proof assistants.
 */
import * as fs from 'fs';
import * as path from 'path';
import { evaluate } from '@stevenvo780/st-lang/api';
import { profileHeader, resolveProfile } from '../utils/profile.js';
import { printSuccess, printError, printInfo, printJSON, FormatOptions } from '../utils/format.js';

export type ExportFormat = 'coq' | 'lean' | 'tptp' | 'json';

export interface ExportOptions extends FormatOptions {
  to: ExportFormat;
  profile?: string;
  output?: string;
}

function wrapAsCoq(source: string, fileName: string): string {
  const lines = source.split('\n').map(l => `  (* ${l} *)`).join('\n');
  return `(* Generated by st-cli from ${fileName} *)
(* Requires Coq 8.x or later *)

Require Import Classical.

(* Source annotation:
${lines}
*)

(* TODO: translate ST derivations to Coq Ltac tactics *)
Theorem placeholder : True.
Proof.
  trivial.
Qed.
`;
}

function wrapAsLean(source: string, fileName: string): string {
  const comment = source.split('\n').map(l => `-- ${l}`).join('\n');
  return `-- Generated by st-cli from ${fileName}
-- Requires Lean 4

${comment}

-- TODO: translate ST derivations to Lean 4 tactics
theorem placeholder : True := trivial
`;
}

function wrapAsTPTP(source: string, fileName: string): string {
  const comment = source.split('\n').map(l => `% ${l}`).join('\n');
  return `% Generated by st-cli from ${fileName}
% TPTP syntax (THF/TFF/FOF)

${comment}

% TODO: translate ST axioms/claims to TPTP fof/thf formulas
fof(placeholder, axiom, ($true)).
`;
}

/** Exported for testability */
export function runExport(filePath: string, opts: ExportOptions): number {
  const fullPath = path.resolve(filePath);
  if (!fs.existsSync(fullPath)) {
    if (opts.json) {
      printJSON({ ok: false, error: `File not found: ${fullPath}` });
    } else {
      printError(`File not found: ${fullPath}`, opts);
    }
    return 1;
  }

  const source = fs.readFileSync(fullPath, 'utf-8');

  // Detect profile from header
  let detectedProfile: string | undefined;
  const headerMatch = /^;;\s*profile:\s*(\S+)/m.exec(source);
  if (headerMatch) detectedProfile = headerMatch[1];

  const profile = opts.profile ?? detectedProfile;
  const resolvedProfile = profile ? (resolveProfile(profile) ?? profile) : 'classical.propositional';

  let fullSource = source;
  if (!/^\s*logic\s+/m.test(source)) {
    fullSource = `${profileHeader(resolvedProfile)}\n${source}`;
  }

  printInfo(`Exporting ${path.basename(fullPath)} to ${opts.to} (profile: ${resolvedProfile})`, opts);

  const format = opts.to;
  const baseName = path.basename(fullPath, path.extname(fullPath));
  const outExt = { coq: 'v', lean: 'lean', tptp: 'p', json: 'json' }[format];
  const outPath = opts.output ?? path.join(path.dirname(fullPath), `${baseName}.${outExt}`);

  let output: string;

  if (format === 'json') {
    const result = evaluate(fullSource, fullPath);
    const jsonOut = {
      file: fullPath,
      profile: resolvedProfile,
      ok: result.ok,
      stdout: result.stdout,
      diagnostics: result.diagnostics,
      results: result.results,
    };
    output = JSON.stringify(jsonOut, null, 2);
  } else if (format === 'coq') {
    output = wrapAsCoq(source, path.basename(fullPath));
  } else if (format === 'lean') {
    output = wrapAsLean(source, path.basename(fullPath));
  } else if (format === 'tptp') {
    output = wrapAsTPTP(source, path.basename(fullPath));
  } else {
    printError(`Unknown format: ${format as string}`, opts);
    return 1;
  }

  fs.writeFileSync(outPath, output, 'utf-8');

  if (opts.json) {
    printJSON({ ok: true, format, outputFile: outPath });
  } else {
    printSuccess(`Exported to ${outPath}`, opts);
  }

  return 0;
}

export function registerExport(program: import('commander').Command): void {
  program
    .command('export <file>')
    .description('Export a .st proof to coq|lean|tptp|json')
    .requiredOption('--to <format>', 'Target format: coq, lean, tptp, json')
    .option('--profile <slug>', 'Logical profile override')
    .option('--output <path>', 'Output file path (default: same dir as input)')
    .option('--json', 'Output result as JSON (does not affect the exported file)')
    .option('-v, --verbose', 'Verbose output')
    .action((file: string, opts: ExportOptions) => {
      const code = runExport(file, opts);
      process.exit(code);
    });
}
