// ============================================================
// Lemas curados — Aritmética de Peano (~20)
// Conmutatividad, asociatividad, distributividad, inducción.
// ============================================================

import type { CuratedLemma } from './types';

export const ARITHMETIC_LEMMAS: CuratedLemma[] = [
  {
    id: 'arith.add-zero-right',
    name: 'Right additive identity',
    statement: '∀n. n + 0 = n',
    domain: 'arithmetic',
    tags: ['peano', 'identity', 'addition', 'naturals'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'arith.add-zero-left',
    name: 'Left additive identity',
    statement: '∀n. 0 + n = n',
    domain: 'arithmetic',
    tags: ['peano', 'identity', 'addition', 'naturals', 'induction'],
    difficulty: 'easy',
  },
  {
    id: 'arith.add-succ-right',
    name: 'Successor on the right of +',
    statement: '∀m n. m + S(n) = S(m + n)',
    domain: 'arithmetic',
    tags: ['peano', 'successor', 'addition', 'naturals'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'arith.add-succ-left',
    name: 'Successor on the left of +',
    statement: '∀m n. S(m) + n = S(m + n)',
    domain: 'arithmetic',
    tags: ['peano', 'successor', 'addition', 'naturals', 'induction'],
    difficulty: 'easy',
  },
  {
    id: 'arith.add-commutative',
    name: 'Commutativity of addition',
    statement: '∀m n. m + n = n + m',
    domain: 'arithmetic',
    tags: ['peano', 'commutativity', 'addition', 'naturals', 'induction'],
    difficulty: 'medium',
  },
  {
    id: 'arith.add-associative',
    name: 'Associativity of addition',
    statement: '∀a b c. (a + b) + c = a + (b + c)',
    domain: 'arithmetic',
    tags: ['peano', 'associativity', 'addition', 'naturals', 'induction'],
    difficulty: 'medium',
  },
  {
    id: 'arith.mul-zero-right',
    name: 'Right multiplicative annihilator',
    statement: '∀n. n · 0 = 0',
    domain: 'arithmetic',
    tags: ['peano', 'zero', 'multiplication', 'naturals'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'arith.mul-zero-left',
    name: 'Left multiplicative annihilator',
    statement: '∀n. 0 · n = 0',
    domain: 'arithmetic',
    tags: ['peano', 'zero', 'multiplication', 'naturals', 'induction'],
    difficulty: 'easy',
  },
  {
    id: 'arith.mul-one-right',
    name: 'Right multiplicative identity',
    statement: '∀n. n · 1 = n',
    domain: 'arithmetic',
    tags: ['peano', 'identity', 'multiplication', 'naturals'],
    difficulty: 'easy',
  },
  {
    id: 'arith.mul-one-left',
    name: 'Left multiplicative identity',
    statement: '∀n. 1 · n = n',
    domain: 'arithmetic',
    tags: ['peano', 'identity', 'multiplication', 'naturals', 'induction'],
    difficulty: 'easy',
  },
  {
    id: 'arith.mul-commutative',
    name: 'Commutativity of multiplication',
    statement: '∀m n. m · n = n · m',
    domain: 'arithmetic',
    tags: ['peano', 'commutativity', 'multiplication', 'naturals', 'induction'],
    difficulty: 'medium',
  },
  {
    id: 'arith.mul-associative',
    name: 'Associativity of multiplication',
    statement: '∀a b c. (a · b) · c = a · (b · c)',
    domain: 'arithmetic',
    tags: ['peano', 'associativity', 'multiplication', 'naturals', 'induction'],
    difficulty: 'medium',
  },
  {
    id: 'arith.mul-distributes-add',
    name: 'Distributivity of · over +',
    statement: '∀a b c. a · (b + c) = a · b + a · c',
    domain: 'arithmetic',
    tags: ['peano', 'distributivity', 'multiplication', 'addition', 'naturals', 'induction'],
    difficulty: 'medium',
  },
  {
    id: 'arith.add-cancel-left',
    name: 'Left cancellation of addition',
    statement: '∀a b c. a + b = a + c → b = c',
    domain: 'arithmetic',
    tags: ['peano', 'cancellation', 'addition', 'naturals', 'induction'],
    difficulty: 'medium',
  },
  {
    id: 'arith.succ-injective',
    name: 'Successor is injective',
    statement: '∀m n. S(m) = S(n) → m = n',
    domain: 'arithmetic',
    tags: ['peano', 'successor', 'injective', 'naturals'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'arith.succ-not-zero',
    name: 'Successor never equals zero',
    statement: '∀n. ¬(S(n) = 0)',
    domain: 'arithmetic',
    tags: ['peano', 'successor', 'zero', 'naturals'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'arith.induction',
    name: 'Mathematical induction',
    statement: '(φ(0) ∧ ∀n. (φ(n) → φ(S(n)))) → ∀n. φ(n)',
    domain: 'arithmetic',
    tags: ['peano', 'induction', 'naturals', 'schema'],
    difficulty: 'hard',
    isAxiom: true,
  },
  {
    id: 'arith.le-reflexive',
    name: 'Reflexivity of ≤',
    statement: '∀n. n ≤ n',
    domain: 'arithmetic',
    tags: ['peano', 'order', 'reflexivity', 'naturals'],
    difficulty: 'trivial',
  },
  {
    id: 'arith.le-transitive',
    name: 'Transitivity of ≤',
    statement: '∀a b c. a ≤ b ∧ b ≤ c → a ≤ c',
    domain: 'arithmetic',
    tags: ['peano', 'order', 'transitivity', 'naturals'],
    difficulty: 'easy',
  },
  {
    id: 'arith.le-antisymmetric',
    name: 'Antisymmetry of ≤',
    statement: '∀a b. a ≤ b ∧ b ≤ a → a = b',
    domain: 'arithmetic',
    tags: ['peano', 'order', 'antisymmetry', 'naturals'],
    difficulty: 'easy',
  },
];
