// ============================================================
// Lemas curados — Lógica de primer orden (~15)
// Cuantificadores: introducción, eliminación, dualidades.
// ============================================================

import type { CuratedLemma } from './types';

export const FIRSTORDER_LEMMAS: CuratedLemma[] = [
  {
    id: 'fol.universal-instantiation',
    name: 'Universal instantiation',
    statement: '∀x. φ(x) → φ(t)',
    domain: 'firstorder',
    tags: ['universal', 'instantiation', 'elimination', 'classical', 'intuitionistic'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'fol.existential-introduction',
    name: 'Existential introduction',
    statement: 'φ(t) → ∃x. φ(x)',
    domain: 'firstorder',
    tags: ['existential', 'introduction', 'classical', 'intuitionistic'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'fol.generalization',
    name: 'Universal generalization',
    statement: '⊢ φ(x) ⇒ ⊢ ∀x. φ(x)',
    domain: 'firstorder',
    tags: ['universal', 'generalization', 'introduction', 'rule'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'fol.forall-and',
    name: 'Universal distributes over conjunction',
    statement: '∀x. (φ(x) ∧ ψ(x)) ↔ (∀x. φ(x)) ∧ (∀x. ψ(x))',
    domain: 'firstorder',
    tags: ['universal', 'conjunction', 'distribution'],
    difficulty: 'medium',
  },
  {
    id: 'fol.exists-or',
    name: 'Existential distributes over disjunction',
    statement: '∃x. (φ(x) ∨ ψ(x)) ↔ (∃x. φ(x)) ∨ (∃x. ψ(x))',
    domain: 'firstorder',
    tags: ['existential', 'disjunction', 'distribution'],
    difficulty: 'medium',
  },
  {
    id: 'fol.duality-forall',
    name: 'Quantifier duality (∀)',
    statement: '∀x. φ(x) ↔ ¬∃x. ¬φ(x)',
    domain: 'firstorder',
    tags: ['duality', 'universal', 'existential', 'negation', 'classical'],
    difficulty: 'medium',
  },
  {
    id: 'fol.duality-exists',
    name: 'Quantifier duality (∃)',
    statement: '∃x. φ(x) ↔ ¬∀x. ¬φ(x)',
    domain: 'firstorder',
    tags: ['duality', 'universal', 'existential', 'negation', 'classical'],
    difficulty: 'medium',
  },
  {
    id: 'fol.not-forall',
    name: 'Negation of universal',
    statement: '¬∀x. φ(x) ↔ ∃x. ¬φ(x)',
    domain: 'firstorder',
    tags: ['negation', 'universal', 'existential', 'classical'],
    difficulty: 'medium',
  },
  {
    id: 'fol.not-exists',
    name: 'Negation of existential',
    statement: '¬∃x. φ(x) ↔ ∀x. ¬φ(x)',
    domain: 'firstorder',
    tags: ['negation', 'universal', 'existential', 'classical', 'intuitionistic'],
    difficulty: 'medium',
  },
  {
    id: 'fol.swap-forall',
    name: 'Universal commutes with itself',
    statement: '∀x ∀y. φ(x,y) ↔ ∀y ∀x. φ(x,y)',
    domain: 'firstorder',
    tags: ['commutativity', 'universal'],
    difficulty: 'easy',
  },
  {
    id: 'fol.swap-exists',
    name: 'Existential commutes with itself',
    statement: '∃x ∃y. φ(x,y) ↔ ∃y ∃x. φ(x,y)',
    domain: 'firstorder',
    tags: ['commutativity', 'existential'],
    difficulty: 'easy',
  },
  {
    id: 'fol.exists-forall-implies-forall-exists',
    name: '∃∀ → ∀∃',
    statement: '(∃y ∀x. φ(x,y)) → (∀x ∃y. φ(x,y))',
    domain: 'firstorder',
    tags: ['quantifier-order', 'universal', 'existential'],
    difficulty: 'medium',
  },
  {
    id: 'fol.equality-reflexive',
    name: 'Reflexivity of equality',
    statement: '∀x. x = x',
    domain: 'firstorder',
    tags: ['equality', 'reflexivity'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'fol.equality-substitution',
    name: 'Substitution of equals',
    statement: '∀x y. x = y → (φ(x) ↔ φ(y))',
    domain: 'firstorder',
    tags: ['equality', 'substitution', 'leibniz'],
    difficulty: 'easy',
    isAxiom: true,
    references: ['Leibniz, indiscernibility'],
  },
  {
    id: 'fol.equality-symmetric',
    name: 'Symmetry of equality',
    statement: '∀x y. x = y → y = x',
    domain: 'firstorder',
    tags: ['equality', 'symmetry'],
    difficulty: 'trivial',
  },
];
