// ============================================================
// Lemas curados — Lógicas modales (~15)
// Axiomas K/T/4/5/B/D + dualidades □/◇.
// ============================================================

import type { CuratedLemma } from './types';

export const MODAL_LEMMAS: CuratedLemma[] = [
  {
    id: 'modal.k',
    name: 'Axiom K (distribution)',
    statement: '□(P → Q) → (□P → □Q)',
    domain: 'modal',
    tags: ['axiom', 'K', 'distribution', 'box', 'normal-modal'],
    difficulty: 'easy',
    isAxiom: true,
    references: ['Kripke, 1963'],
  },
  {
    id: 'modal.t',
    name: 'Axiom T (reflexivity)',
    statement: '□P → P',
    domain: 'modal',
    tags: ['axiom', 'T', 'reflexivity', 'box'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'modal.4',
    name: 'Axiom 4 (transitivity)',
    statement: '□P → □□P',
    domain: 'modal',
    tags: ['axiom', '4', 'transitivity', 'box', 'S4'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'modal.5',
    name: 'Axiom 5 (euclidean)',
    statement: '◇P → □◇P',
    domain: 'modal',
    tags: ['axiom', '5', 'euclidean', 'diamond', 'box', 'S5'],
    difficulty: 'medium',
    isAxiom: true,
  },
  {
    id: 'modal.b',
    name: 'Axiom B (symmetry)',
    statement: 'P → □◇P',
    domain: 'modal',
    tags: ['axiom', 'B', 'symmetry', 'box', 'diamond'],
    difficulty: 'medium',
    isAxiom: true,
  },
  {
    id: 'modal.d',
    name: 'Axiom D (serial)',
    statement: '□P → ◇P',
    domain: 'modal',
    tags: ['axiom', 'D', 'serial', 'box', 'diamond'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'modal.duality-box',
    name: 'Modal duality (box)',
    statement: '□P ↔ ¬◇¬P',
    domain: 'modal',
    tags: ['duality', 'box', 'diamond', 'negation', 'definition'],
    difficulty: 'easy',
  },
  {
    id: 'modal.duality-diamond',
    name: 'Modal duality (diamond)',
    statement: '◇P ↔ ¬□¬P',
    domain: 'modal',
    tags: ['duality', 'box', 'diamond', 'negation', 'definition'],
    difficulty: 'easy',
  },
  {
    id: 'modal.necessitation',
    name: 'Necessitation rule',
    statement: '⊢ P ⇒ ⊢ □P',
    domain: 'modal',
    tags: ['rule', 'necessitation', 'box', 'normal-modal'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'modal.box-and',
    name: 'Box distributes over conjunction',
    statement: '□(P ∧ Q) ↔ (□P ∧ □Q)',
    domain: 'modal',
    tags: ['distribution', 'box', 'conjunction', 'normal-modal'],
    difficulty: 'medium',
  },
  {
    id: 'modal.diamond-or',
    name: 'Diamond distributes over disjunction',
    statement: '◇(P ∨ Q) ↔ (◇P ∨ ◇Q)',
    domain: 'modal',
    tags: ['distribution', 'diamond', 'disjunction', 'normal-modal'],
    difficulty: 'medium',
  },
  {
    id: 'modal.box-conjunction-intro',
    name: 'Box conjunction introduction',
    statement: '(□P ∧ □Q) → □(P ∧ Q)',
    domain: 'modal',
    tags: ['introduction', 'box', 'conjunction', 'normal-modal'],
    difficulty: 'easy',
  },
  {
    id: 'modal.s5-collapse',
    name: 'S5 modality collapse',
    statement: '◇□P → □P',
    domain: 'modal',
    tags: ['S5', 'collapse', 'diamond', 'box'],
    difficulty: 'hard',
  },
  {
    id: 'modal.contingency',
    name: 'Contingency definition',
    statement: 'Contingent(P) ↔ (◇P ∧ ◇¬P)',
    domain: 'modal',
    tags: ['definition', 'contingency', 'diamond', 'negation'],
    difficulty: 'easy',
  },
  {
    id: 'modal.box-mp',
    name: 'Box modus ponens',
    statement: '(□P ∧ □(P → Q)) → □Q',
    domain: 'modal',
    tags: ['modus-ponens', 'box', 'implication', 'normal-modal'],
    difficulty: 'easy',
  },
];
