// ============================================================
// Lemas curados — Lógica proposicional clásica (~30)
// Identidades, De Morgan, contraposición, distributividad, etc.
// ============================================================

import type { CuratedLemma } from './types';

export const PROPOSITIONAL_LEMMAS: CuratedLemma[] = [
  {
    id: 'prop.identity',
    name: 'Identity',
    statement: 'P → P',
    domain: 'propositional',
    tags: ['identity', 'implication', 'classical', 'intuitionistic'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.double-negation-elim',
    name: 'Double negation elimination',
    statement: '¬¬P → P',
    domain: 'propositional',
    tags: ['negation', 'classical', 'double-negation'],
    difficulty: 'easy',
  },
  {
    id: 'prop.double-negation-intro',
    name: 'Double negation introduction',
    statement: 'P → ¬¬P',
    domain: 'propositional',
    tags: ['negation', 'classical', 'intuitionistic', 'double-negation'],
    difficulty: 'easy',
  },
  {
    id: 'prop.excluded-middle',
    name: 'Law of excluded middle',
    statement: 'P ∨ ¬P',
    domain: 'propositional',
    tags: ['classical', 'tertium-non-datur', 'disjunction', 'negation'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'prop.non-contradiction',
    name: 'Law of non-contradiction',
    statement: '¬(P ∧ ¬P)',
    domain: 'propositional',
    tags: ['classical', 'intuitionistic', 'negation', 'conjunction'],
    difficulty: 'easy',
  },
  {
    id: 'prop.de-morgan-and',
    name: 'De Morgan (conjunction)',
    statement: '¬(P ∧ Q) ↔ (¬P ∨ ¬Q)',
    domain: 'propositional',
    tags: ['de-morgan', 'duality', 'classical', 'conjunction', 'disjunction', 'negation'],
    difficulty: 'easy',
    references: ['De Morgan, 1860'],
  },
  {
    id: 'prop.de-morgan-or',
    name: 'De Morgan (disjunction)',
    statement: '¬(P ∨ Q) ↔ (¬P ∧ ¬Q)',
    domain: 'propositional',
    tags: ['de-morgan', 'duality', 'classical', 'intuitionistic', 'disjunction', 'negation'],
    difficulty: 'easy',
    references: ['De Morgan, 1860'],
  },
  {
    id: 'prop.contraposition',
    name: 'Contraposition',
    statement: '(P → Q) ↔ (¬Q → ¬P)',
    domain: 'propositional',
    tags: ['contraposition', 'classical', 'implication', 'negation'],
    difficulty: 'easy',
  },
  {
    id: 'prop.modus-ponens',
    name: 'Modus ponens',
    statement: '((P → Q) ∧ P) → Q',
    domain: 'propositional',
    tags: ['modus-ponens', 'inference', 'classical', 'intuitionistic', 'implication'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'prop.modus-tollens',
    name: 'Modus tollens',
    statement: '((P → Q) ∧ ¬Q) → ¬P',
    domain: 'propositional',
    tags: ['modus-tollens', 'inference', 'classical', 'implication', 'negation'],
    difficulty: 'easy',
  },
  {
    id: 'prop.hypothetical-syllogism',
    name: 'Hypothetical syllogism',
    statement: '((P → Q) ∧ (Q → R)) → (P → R)',
    domain: 'propositional',
    tags: ['syllogism', 'transitivity', 'classical', 'intuitionistic', 'implication'],
    difficulty: 'easy',
  },
  {
    id: 'prop.disjunctive-syllogism',
    name: 'Disjunctive syllogism',
    statement: '((P ∨ Q) ∧ ¬P) → Q',
    domain: 'propositional',
    tags: ['syllogism', 'classical', 'disjunction', 'negation'],
    difficulty: 'easy',
  },
  {
    id: 'prop.and-commutative',
    name: 'Commutativity of conjunction',
    statement: '(P ∧ Q) ↔ (Q ∧ P)',
    domain: 'propositional',
    tags: ['commutativity', 'classical', 'intuitionistic', 'conjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.or-commutative',
    name: 'Commutativity of disjunction',
    statement: '(P ∨ Q) ↔ (Q ∨ P)',
    domain: 'propositional',
    tags: ['commutativity', 'classical', 'intuitionistic', 'disjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.and-associative',
    name: 'Associativity of conjunction',
    statement: '((P ∧ Q) ∧ R) ↔ (P ∧ (Q ∧ R))',
    domain: 'propositional',
    tags: ['associativity', 'classical', 'intuitionistic', 'conjunction'],
    difficulty: 'easy',
  },
  {
    id: 'prop.or-associative',
    name: 'Associativity of disjunction',
    statement: '((P ∨ Q) ∨ R) ↔ (P ∨ (Q ∨ R))',
    domain: 'propositional',
    tags: ['associativity', 'classical', 'intuitionistic', 'disjunction'],
    difficulty: 'easy',
  },
  {
    id: 'prop.and-idempotent',
    name: 'Idempotence of conjunction',
    statement: '(P ∧ P) ↔ P',
    domain: 'propositional',
    tags: ['idempotence', 'classical', 'intuitionistic', 'conjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.or-idempotent',
    name: 'Idempotence of disjunction',
    statement: '(P ∨ P) ↔ P',
    domain: 'propositional',
    tags: ['idempotence', 'classical', 'intuitionistic', 'disjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.and-distributes-over-or',
    name: 'Conjunction distributes over disjunction',
    statement: '(P ∧ (Q ∨ R)) ↔ ((P ∧ Q) ∨ (P ∧ R))',
    domain: 'propositional',
    tags: ['distributivity', 'classical', 'intuitionistic', 'conjunction', 'disjunction'],
    difficulty: 'medium',
  },
  {
    id: 'prop.or-distributes-over-and',
    name: 'Disjunction distributes over conjunction',
    statement: '(P ∨ (Q ∧ R)) ↔ ((P ∨ Q) ∧ (P ∨ R))',
    domain: 'propositional',
    tags: ['distributivity', 'classical', 'intuitionistic', 'conjunction', 'disjunction'],
    difficulty: 'medium',
  },
  {
    id: 'prop.absorption-and',
    name: 'Absorption (∧ over ∨)',
    statement: '(P ∧ (P ∨ Q)) ↔ P',
    domain: 'propositional',
    tags: ['absorption', 'classical', 'intuitionistic', 'conjunction', 'disjunction'],
    difficulty: 'easy',
  },
  {
    id: 'prop.absorption-or',
    name: 'Absorption (∨ over ∧)',
    statement: '(P ∨ (P ∧ Q)) ↔ P',
    domain: 'propositional',
    tags: ['absorption', 'classical', 'intuitionistic', 'conjunction', 'disjunction'],
    difficulty: 'easy',
  },
  {
    id: 'prop.implication-as-or',
    name: 'Implication as disjunction',
    statement: '(P → Q) ↔ (¬P ∨ Q)',
    domain: 'propositional',
    tags: ['implication', 'classical', 'disjunction', 'negation', 'definition'],
    difficulty: 'easy',
  },
  {
    id: 'prop.biconditional-def',
    name: 'Biconditional definition',
    statement: '(P ↔ Q) ↔ ((P → Q) ∧ (Q → P))',
    domain: 'propositional',
    tags: ['biconditional', 'classical', 'intuitionistic', 'implication', 'conjunction'],
    difficulty: 'easy',
  },
  {
    id: 'prop.ex-falso',
    name: 'Ex falso quodlibet',
    statement: '⊥ → P',
    domain: 'propositional',
    tags: ['ex-falso', 'explosion', 'classical', 'intuitionistic', 'bottom'],
    difficulty: 'easy',
    isAxiom: true,
  },
  {
    id: 'prop.peirce',
    name: "Peirce's law",
    statement: '((P → Q) → P) → P',
    domain: 'propositional',
    tags: ['peirce', 'classical', 'implication'],
    difficulty: 'hard',
    references: ['Peirce, 1885'],
  },
  {
    id: 'prop.weakening',
    name: 'Weakening',
    statement: 'P → (Q → P)',
    domain: 'propositional',
    tags: ['weakening', 'classical', 'intuitionistic', 'implication'],
    difficulty: 'trivial',
    isAxiom: true,
  },
  {
    id: 'prop.and-elim-left',
    name: 'Conjunction elimination (left)',
    statement: '(P ∧ Q) → P',
    domain: 'propositional',
    tags: ['elimination', 'classical', 'intuitionistic', 'conjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.and-elim-right',
    name: 'Conjunction elimination (right)',
    statement: '(P ∧ Q) → Q',
    domain: 'propositional',
    tags: ['elimination', 'classical', 'intuitionistic', 'conjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.or-intro-left',
    name: 'Disjunction introduction (left)',
    statement: 'P → (P ∨ Q)',
    domain: 'propositional',
    tags: ['introduction', 'classical', 'intuitionistic', 'disjunction'],
    difficulty: 'trivial',
  },
  {
    id: 'prop.or-intro-right',
    name: 'Disjunction introduction (right)',
    statement: 'Q → (P ∨ Q)',
    domain: 'propositional',
    tags: ['introduction', 'classical', 'intuitionistic', 'disjunction'],
    difficulty: 'trivial',
  },
];
