// ============================================================
// Lemas curados — Teoría de conjuntos (~15)
// Álgebra booleana sobre ∪, ∩, ⊆, complemento.
// ============================================================

import type { CuratedLemma } from './types';

export const SET_THEORY_LEMMAS: CuratedLemma[] = [
  {
    id: 'set.union-commutative',
    name: 'Commutativity of union',
    statement: '∀A B. A ∪ B = B ∪ A',
    domain: 'set',
    tags: ['commutativity', 'union', 'boolean-algebra'],
    difficulty: 'trivial',
  },
  {
    id: 'set.inter-commutative',
    name: 'Commutativity of intersection',
    statement: '∀A B. A ∩ B = B ∩ A',
    domain: 'set',
    tags: ['commutativity', 'intersection', 'boolean-algebra'],
    difficulty: 'trivial',
  },
  {
    id: 'set.union-associative',
    name: 'Associativity of union',
    statement: '∀A B C. (A ∪ B) ∪ C = A ∪ (B ∪ C)',
    domain: 'set',
    tags: ['associativity', 'union', 'boolean-algebra'],
    difficulty: 'easy',
  },
  {
    id: 'set.inter-associative',
    name: 'Associativity of intersection',
    statement: '∀A B C. (A ∩ B) ∩ C = A ∩ (B ∩ C)',
    domain: 'set',
    tags: ['associativity', 'intersection', 'boolean-algebra'],
    difficulty: 'easy',
  },
  {
    id: 'set.union-distributes-inter',
    name: 'Distributivity of ∪ over ∩',
    statement: '∀A B C. A ∪ (B ∩ C) = (A ∪ B) ∩ (A ∪ C)',
    domain: 'set',
    tags: ['distributivity', 'union', 'intersection', 'boolean-algebra'],
    difficulty: 'medium',
  },
  {
    id: 'set.inter-distributes-union',
    name: 'Distributivity of ∩ over ∪',
    statement: '∀A B C. A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C)',
    domain: 'set',
    tags: ['distributivity', 'union', 'intersection', 'boolean-algebra'],
    difficulty: 'medium',
  },
  {
    id: 'set.de-morgan-union',
    name: 'De Morgan (union)',
    statement: '∀A B. (A ∪ B)ᶜ = Aᶜ ∩ Bᶜ',
    domain: 'set',
    tags: ['de-morgan', 'union', 'complement', 'duality', 'boolean-algebra'],
    difficulty: 'medium',
    references: ['De Morgan, 1860'],
  },
  {
    id: 'set.de-morgan-inter',
    name: 'De Morgan (intersection)',
    statement: '∀A B. (A ∩ B)ᶜ = Aᶜ ∪ Bᶜ',
    domain: 'set',
    tags: ['de-morgan', 'intersection', 'complement', 'duality', 'boolean-algebra'],
    difficulty: 'medium',
    references: ['De Morgan, 1860'],
  },
  {
    id: 'set.union-idempotent',
    name: 'Idempotence of union',
    statement: '∀A. A ∪ A = A',
    domain: 'set',
    tags: ['idempotence', 'union', 'boolean-algebra'],
    difficulty: 'trivial',
  },
  {
    id: 'set.inter-idempotent',
    name: 'Idempotence of intersection',
    statement: '∀A. A ∩ A = A',
    domain: 'set',
    tags: ['idempotence', 'intersection', 'boolean-algebra'],
    difficulty: 'trivial',
  },
  {
    id: 'set.union-empty',
    name: 'Union with empty set',
    statement: '∀A. A ∪ ∅ = A',
    domain: 'set',
    tags: ['identity', 'union', 'empty-set'],
    difficulty: 'trivial',
  },
  {
    id: 'set.inter-empty',
    name: 'Intersection with empty set',
    statement: '∀A. A ∩ ∅ = ∅',
    domain: 'set',
    tags: ['annihilator', 'intersection', 'empty-set'],
    difficulty: 'trivial',
  },
  {
    id: 'set.subset-reflexive',
    name: 'Reflexivity of ⊆',
    statement: '∀A. A ⊆ A',
    domain: 'set',
    tags: ['reflexivity', 'subset', 'order'],
    difficulty: 'trivial',
  },
  {
    id: 'set.subset-transitive',
    name: 'Transitivity of ⊆',
    statement: '∀A B C. A ⊆ B ∧ B ⊆ C → A ⊆ C',
    domain: 'set',
    tags: ['transitivity', 'subset', 'order'],
    difficulty: 'easy',
  },
  {
    id: 'set.extensionality',
    name: 'Axiom of extensionality',
    statement: '∀A B. (∀x. x ∈ A ↔ x ∈ B) → A = B',
    domain: 'set',
    tags: ['zfc', 'extensionality', 'axiom', 'equality'],
    difficulty: 'easy',
    isAxiom: true,
    references: ['Zermelo, 1908'],
  },
];
